# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
destination:      ./_gh_pages
exclude:          [".editorconfig", ".gitignore", ".ruby-version", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "less"]
port:             9001

# Custom vars
repo:             https://github.com/jasny/bootstrap
download:         https://github.com/jasny/bootstrap/archive/v3.0.0.zip
download_dist:    https://github.com/jasny/bootstrap/releases/download/v3.0.0/bootstrap-3.0.0-dist.zip

blog:             http://blog.getbootstrap.com
expo:             http://expo.getbootstrap.com

cdn_css:          //cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.0.0-p7/css/bootstrap.min.css
cdn_theme_css:    //cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.0.0-p7/css/bootstrap-theme.min.css
cdn_js:           //cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.0.0-p7/js/bootstrap.min.js
